# Generated by Django 6.1 on 2026-08-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, help_text='E.g., Software Engineer, Project Manager', max_length=100),
        ),
    ]
